package com.sphoton.hoangviet.sixmin.managers;

import android.content.Context;

import com.google.android.gms.analytics.ExceptionReporter;
import com.google.android.gms.analytics.GoogleAnalytics;
import com.google.android.gms.analytics.Tracker;
import com.sphoton.hoangviet.sixmin.R;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

/**
 * A collection of Google Analytics trackers. Fetch the tracker you need using
 * {@code AnalyticsTrackers.getInstance().get(...)}
 * <p>
 * This code was generated by Android Studio but can be safely modified by
 * hand at this point.
 * <p>
 * before using this!
 */
public final class AnalyticsTrackers {
    private static Tracker tracker;

    public static synchronized Tracker getTracker(Context mContext) {
        if(tracker ==null) {
            tracker = GoogleAnalytics.getInstance(mContext).newTracker(R.xml.app_tracker);

            ArrayList<String> packages = new ArrayList<String>();
            packages.add("com.sphoton.hoangviet.sixmin");
            ExceptionReporter reporter = new ExceptionReporter(tracker, Thread.getDefaultUncaughtExceptionHandler(), mContext);
            reporter.setExceptionParser(new AnalyticsExceptionParser(mContext, packages));
            Thread.setDefaultUncaughtExceptionHandler(reporter);

        }

        return tracker;
    }
}
